name: ClassVoiceMonitor Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        # 确保安装正确版本的numpy
        pip install numpy==1.24.3
        
    - name: Build executable
      run: |
        pyinstaller -D -w -n ClassVoiceMonitor ^
          --hidden-import=numpy.core._multiarray_umath ^
          --hidden-import=numpy.core._multiarray_tests ^
          --collect-all numpy ^
          ClassVoiceMonitor.py
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ClassVoiceMonitor-windows
        path: dist/ClassVoiceMonitor/
